# Configure the build matrix
matrix:
  include:
  # Validation
  - env: TEST=validation
    php: 7.2
  # PostgreSQL / various PHP
  - env: TEST=pgsql
    php: 7.1
  - env: TEST=pgsql
    php: 7.2
  # MySQL / various PHP
  - env: TEST=mysql
    php: 7.1
  - env: TEST=mysql
    php: 7.2
  # Path info disabled
  - env: TEST=mysql DISABLE_PATH_INFO=1
    php: 7.2
env:
  global:
  - secure: "nxosaZUBRaYhk8+LHaDnVgMIveiK4zewiXW5Fw5TtB/D6V67oASufil1uhcayyzIBwnrZZmrFPLhXm0Lm1RiQHrsftffcMB5JlWK9R9EyWpyd87ewqWy3kXBAvsXXTU6ihGiaFpklhVCKt7XcDSR8bWEb2NVWrM7JS7dHDKMwaA="
language: php
dist: trusty
python:
<<<<<<< HEAD
  - 3.3
=======
  - 3.3 # Required by Javascript linter/builder
>>>>>>> ojs-3_1_2-1
git:
  # Inhibit automatic submodule checkout (see below)
  submodules: false
cache: npm
addons:
<<<<<<< HEAD
  firefox: "45.9.0esr"
=======
  firefox: "45.9.0esr" # Required by Selenium tests
>>>>>>> ojs-3_1_2-1
  apt:
    update: true
before_install:
  # Check out submodules (this script checks out developer forks if necessary)
  - ./tools/startSubmodulesTRAVIS.sh

  - |
    if [[ "$TEST" != "validation" ]]; then
      # Prepare for unit and integration tests.

      # Prepare the server environment
      ./lib/pkp/tools/travis/prepare-webserver.sh
      source ./lib/pkp/tools/travis/start-xvfb.sh
      ./lib/pkp/tools/travis/start-selenium.sh

      # Prepare the local codebase
      ./lib/pkp/tools/travis/install-composer-dependencies.sh
      npm install && npm run build
    else
      # Prepare for validation tests.
      ./lib/pkp/tools/travis/install-linter.sh
    fi

  # The code coverage test is only performed in the MySQL test round.
  - if [[ "$TEST" == "mysql" ]]; then ./lib/pkp/tools/travis/prepare-code-coverage.sh; fi

script:
  - |
    if [[ "$TEST" != "validation" ]]; then
      # Run the unit and integration tests.
      source ./lib/pkp/tools/travis/prepare-tests.sh
      ./lib/pkp/tools/travis/run-tests.sh
    else
      # Run the validation tests.
      ./lib/pkp/tools/travis/validate-xml.sh
      ./lib/pkp/tools/buildjs.sh -n
      ./lib/pkp/tools/checkHelp.sh
    fi

after_script:
  # Merge the coverage reports into one HTML report and upload to http://pkp.sfu.ca/test-coverage
  - if [[ "$TEST" == "mysql" ]]; then ./lib/pkp/tools/travis/post-code-coverage.sh; fi

  # Upload the completed database to the PKP server for other uses
  - if [[ "$TEST" != "validation" ]]; then ./lib/pkp/tools/travis/post-data-build.sh; fi

  # Print logs and outputs for debugging.
  - tail -n 200 error.log
  - cat ./lib/pkp/tests/results/error.log
#  - sudo apt-get install sharutils
#  - test "$(ls -A lib/pkp/tests/results | grep .png)" && (tar cz lib/pkp/tests/results/*.png | uuencode /dev/stdout)
